steps:
  # Grab cached M2 repo
  - name: gcr.io/cloud-builders/gsutil
    id: Get M2 Cache
    args: ['cp', 'gs://ons-ci-int-cloudbuild-maven-cache/m2.tar.gz', 'm2.tar.gz']
      #
  # See https://github.com/GoogleCloudPlatform/cloud-builders-community to get the tar command
  - name: europe-west2-docker.pkg.dev/ons-ci-int/int-docker-ci/cloudbuild/tar
    id: Expand M2 Cache
    args: ['xpzf', 'm2.tar.gz']

  - name: 'maven:3-jdk-11'
    id: Maven install
    env:
      - TZ=Europe/London
    args: ['-Dmaven.repo.local=/workspace/.m2/repository', '-DskipTests', 'install']
    entrypoint: mvn

  # Update M2 repo cache
  - name: europe-west2-docker.pkg.dev/ons-ci-int/int-docker-ci/cloudbuild/tar
    id: Compress M2 Cache
    args: ['cpzf', 'm2.tar.gz', '.m2']

  - name: gcr.io/cloud-builders/gsutil
    id: Save M2 Cache
    args: ['cp', 'm2.tar.gz', 'gs://ons-ci-int-cloudbuild-maven-cache/m2.tar.gz']

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
    - '-eEuo'
    - 'pipefail'
    - '-c'
    - |-
      ls -al
      rm -rf .m2
      rm m2.tar.gz
      ls -al

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'europe-west2-docker.pkg.dev/ons-ci-int/int-docker-snapshot/rh-cucumber:$BRANCH_NAME-$SHORT_SHA', '-f', 'cloudbuild.docker', '.' ]

timeout: '2400s'
images: [ 'europe-west2-docker.pkg.dev/ons-ci-int/int-docker-snapshot/rh-cucumber:$BRANCH_NAME-$SHORT_SHA' ]




